### ISSUE TITLE
Switches

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [ercanersoy/DOS-Coreutils#1]
By default UPX does not generate 8086 compatible executables, so it is useless to use -0 in WCC. I would add to UPX following, to enhance compression too:
--8086 --ultra-brute --crp-ms=999999

For WCC, I will enhance performance with my usual switches, also generating COM files instead of EXE ones:
-oneatx -ohirbk -ol -ol+ -oi -ei -zp4 -0 -mt -s -ri /bt=dos /l=com

**Comment by ercanersoy** [comment]
Thanks. But, these parameters of wcc has errors.

**Comment by javiergutierrezchamorro** [comment]
Sorry, there were WCL parameters. Ones starting with / belong to wlink, the others to WCC.
Which errors did they get?

**Comment by ercanersoy** [comment]
I get -mt parameter error. (E1073 Invalid Option)

**Comment by javiergutierrezchamorro** [comment]
It is strange, because with WCL works. Maybe you can use -ms and then force it to a .COM y wlink too.
By the way, I add also to link /"OPTION ELIMINATE" /"OPTION VFREMOVAL"

**Comment by javiergutierrezchamorro** [comment]
Confirmed, -ms is suitable for .COM files. Only thing, is that for compatibility reasons WCL accepted -mt, and transformed it to -ms when  calling WCC:
https://sourceforge.net/p/freedos/mailman/message/5113638/
https://github.com/open-watcom/open-watcom-v2/issues/275

**Comment by ercanersoy** [comment]
I get this error: directive error near -ms

LD = wlink
LDFLAGS = option eliminate option vfremoval -ms
$(LD) $(LDFLAGS) file commands\beep.obj

**Comment by javiergutierrezchamorro** [comment]
-ms is the memory mode switch for the compiler WCC, not the linker

**Comment by ercanersoy** [comment]
Thanks. But, I don't get .COM files instead of .EXE files. I get .EXE files.

**Comment by javiergutierrezchamorro** [comment]
You need to instruct wlink to generate a COM file:
https://sourceforge.net/p/freedos/mailman/freedos-devel/thread/2.7.10.ABPP.HSJAAH%40belous.munic.msk.su/

**Comment by ercanersoy** [comment]
![virtualbox_windows xp_23_06_2017_11_16_32](https://user-images.githubusercontent.com/15850068/27472828-961baf44-5805-11e7-8ac7-b9b67d7ad5db.png)

**Comment by ercanersoy** [comment]
I get warnings (W1008) and undefined reference errors (E2028).

**Comment by javiergutierrezchamorro** [comment]
Can you post the whole details?

**Comment by ercanersoy** [comment]
Open Watcom Make Version 1.9
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	wcc -oneatx -ohirbk -ol -ol+ -oi -ei -zp4 -0 -s -ri -ms /bt=dos commands\beep.c -fo=commands\beep.obj
Open Watcom C16 Optimizing Compiler Version 1.9
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
commands\beep.c: 64 lines, included 3968, 0 warnings, 0 errors
Code size: 340
	wlink option eliminate option vfremoval form dos com file commands\beep.obj
Open Watcom Linker Version 1.9
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
loading object files
searching libraries
Warning! W1008: cannot open graph.lib : file not found
Warning! W1008: cannot open clibs.lib : file not found
Warning! W1008: cannot open math87s.lib : file not found
Warning! W1008: cannot open emu87.lib : file not found
Error! E2028: puts_ is an undefined reference
Error! E2028: atoi_ is an undefined reference
Error! E2028: sound_ is an undefined reference
Error! E2028: delay_ is an undefined reference
Error! E2028: nosound_ is an undefined reference
Error! E2028: _cstart_ is an undefined reference
Error! E2028: _small_code_ is an undefined reference
Error! E2028: __argc is an undefined reference
Warning! W1023: no starting address found, using 0000:0000
creating a DOS .COM executable

**Comment by ercanersoy** [comment]
Open Watcom Make Version 1.9
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	wlink system dos format dos com option eliminate option vfremoval file commands\beep.obj
Open Watcom Linker Version 1.9
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
Error! E3057: executable format has been established

**Comment by javiergutierrezchamorro** [comment]
I would suggest reading OC documentation. I did it for you and this worked with your makefile in OC 2.0:
LDFLAGS = option eliminate option vfremoval system com

But, for instance clear, is using graph.lib, which requires large memory model, and does not support COM files, not a good idea.. Better something like:
void cls(void); 
#pragma aux cls= \ 
  " mov ah, 0fh " \ 
  " int 10h " \ 
  " xor ah, ah " \ 
  " int 10h " ;

**Comment by javiergutierrezchamorro** [comment]
Same for ls.c, better if you avoid graph.lib, which is neither intended for textmode.

**Comment by ercanersoy** [comment]
I get warnings for time.c.

**Comment by ercanersoy** [comment]
Thanks. I recompiled clear.c, ls.c and time.c as .exe file.
