### ISSUE TITLE
Move MAX_COMMAND_LINE_LENGTH definition

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [ercanersoy/DOS-Coreutils#2]
I would recommend moving define MAX_COMMAND_LINE_LENGTH in sh.c to dosc.h, so it can be reused in different modules.

**Comment by ercanersoy** [comment]
I have solved this issue.

**Comment by javiergutierrezchamorro** [comment]
Not closed. Still in use in time.c and others.

**Comment by ercanersoy** [comment]
I have fixed it.
