### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [ercanersoy/DOS-Coreutils#7]
I have performed a simple lint against the project, and code seems quite buggy. I will recommend you taking care about this.

date.c(43): Condition 'argc>=2' is always true

pwd.c(17): Memory leak: buffer
pwd.c(25): Memory leak: buffer

rm.c(11): Variable 'item_name' is reassigned a value before the old one has been used.
rm.c(17): Memory leak: item_name

sh.c(35): The obsolete function 'gets' is called. With 'gets' you'll get a buffer overrun if the input data exceeds the size of the buffer. It is recommended to use the functions 'fgets' or 'gets_s' instead.

time.c(53): %llf in format string (no. 1) requires 'double' but the argument type is 'long double'.
time.c(61): Memory leak: command_line

**Comment by ercanersoy** [comment]
These issues has been fixed.
